name: Bug report
description: Report a reproducible defect
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes: { label: Summary }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Reproduction steps }
    validations: { required: true }
